require("user.vim-config.functions")
require("user.vim-config.options")
require("user.vim-config.keymaps")
require("user.lazy_plugins_init")
require("user.vim-config.post_plugins")
require("user.vim-config.autocmd")
