require("user.vim-config.options")
require("user.vim-config.keymaps")
require("user.lazy_plugins_init")
require("user.vim-config.colors")
-- require("user.plugins-config.vimtex-config")
require("user.vim-config.autocmd")
